//UI Actions
export const SHOW_LOADING = 'SHOW_LOADING'
export const HIDE_LOADING = 'HIDE_LOADING'
export const ORIENTATION_CHANGED = 'ORIENTATION_CHANGED'

//Login Actions
export const SHOW_LOADING_LOGIN = 'SHOW_LOADING_LOGIN'
export const HIDE_LOADING_LOGIN = 'HIDE_LOADING_LOGIN'
export const SHOW_LOGIN_ERROR_MESSAGE = 'SHOW_LOGIN_ERROR_MESSAGE'
export const HIDE_LOGIN_ERROR_MESSAGE = 'SHOW_LOGIN_ERROR_MESSAGE'
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO'


//Search Actions
export const RETRIEVE_HOTELS_LIST = 'RETRIEVE_HOTELS_LIST'
export const CLEAN_HOTELS = 'CLEAN_HOTELS'
export const LOGOUT = 'LOGOUT'

//Favorites
export const CLEAN_FAVORITES = 'CLEAN_FAVORITES'
export const RETRIEVE_FAVOURITES = 'RETRIEVE_FAVOURITES'

